{{- range .Values.nodePools }}
apiVersion: karpenter.sh/{{ $.Values.karpenterApiVersion | default "v1" }}
kind: NodePool
metadata:
  name: {{ .name }}
spec:
  template:
    metadata:
      labels:
        applicationName: {{ .applicationName | default "" }}
        phrase.com/karpenter-nodepool: {{ .name }}
        {{- if .labels }}
        {{- range $key, $value := .labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      nodeClassRef:
      {{- if eq $.Values.karpenterApiVersion "v1beta1" }}
        apiVersion: karpenter.k8s.aws/v1beta1
      {{- end }}
      {{- if eq $.Values.karpenterApiVersion "v1" }}
        group: karpenter.k8s.aws
      {{- end }}
        kind: "EC2NodeClass"
        name: {{ .providerName }}
      requirements:
          - key: karpenter.sh/capacity-type
            operator: In
            values: [{{ range $index, $value := .capacityType }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
          {{- if .instanceFamily }}
          - key: karpenter.k8s.aws/instance-family
            operator: In
            values: [{{ range $index, $value := .instanceFamily }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
          {{- end }}
          {{- if .instanceType }}
          - key: node.kubernetes.io/instance-type
            operator: In
            values: [{{ range $index, $value := .instanceType }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
          {{- end }}
          {{- if .arch }}
          - key: kubernetes.io/arch
            operator: In
            values: [{{ range $index, $value := .arch }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
          {{- end }}
      {{- if .taints }}
      taints:
      {{- range .taints }}
          - effect: {{ default "NoSchedule" .effect | quote }}
            key: {{ .key | quote }}
            value: {{ .value | quote }}
      {{- end }}
      {{- end }}
      {{- if .startupTaints }}
      startupTaints:
      {{- range .startupTaints }}
          - effect: {{ default "NoExecute" .effect | quote }}
            key: {{ .key | quote }}
            value: {{ .value | quote }}
      {{- end }}
      {{- end }}
  limits:
    {{- if .gpuLimit }}
    memory: {{ mul 16 .gpuLimit }}Gi
    {{- end }}
    {{- if .cpuLimit }}
    cpu: {{ .cpuLimit }}
    {{- end }}
  {{ if .consolidationPolicy }}
  disruption:
    consolidationPolicy: {{ .consolidationPolicy }}
  {{- end }}
---
{{- end }}
