{{- range .Values.provisioners }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .name }}
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: [{{ range $index, $value := .capacityType }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [{{ range $index, $value := .instanceFamily }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
    {{- if .instanceType }}
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [{{ range $index, $value := .instanceType }}{{ if $index }}, {{ end }}{{ $value | quote }}{{ end }}]
    {{- end }}
  {{- if .taints }}
  taints:
  {{- range .taints }}
    - effect: {{ default "NoSchedule" .effect | quote }}
      key: {{ .key | quote }}
      value: {{ .value | quote }}
  {{- end }}
  {{- end }}
  {{- if .startupTaints }}
  startupTaints:
  {{- range .startupTaints }}
    - effect: {{ default "NoExecute" .effect | quote }}
      key: {{ .key | quote }}
      value: {{ .value | quote }}
  {{- end }}
  {{- end }}
  limits:
    resources:
      {{- if .gpuLimit }}
      memory: {{ mul 16 .gpuLimit }}Gi
      {{- end }}
      {{- if .cpuLimit }}
      cpu: {{ .cpuLimit }}
      {{- end }}
  labels:
    applicationName: {{ .applicationName | default "" }}
    phrase.com/karpenter-nodepool: {{ .name }}
    {{- if .labels }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  providerRef:
    name: {{ .providerName }}
  ttlSecondsUntilExpired: {{ .ttlSecondsUntilExpired | default 2592000 }} # 30 days by default
  consolidation:
      enabled: {{ .consolidationEnabled }}
---
{{- end }}
